version: "3.1"

language: en

pipeline:
- name: SpacyNLP
  model: "en_core_web_sm"    # Spacy model to use
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper

policies:
- name: RulePolicy
- name: MemoizationPolicy
- name: TEDPolicy
  epochs: 100

# Remove if not necessary
# assistant_id: 20240904-212717-polite-dormer
#assistant_id: 20240904-223740-wooden-circuit
#assistant_id: 20240904-224624-closed-quarter
assistant_id: 20240904-225949-joint-pile
